// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XdJcrKnQLT4Of1uJZ8VhS-D2kIUTc1s',
    appId: '1:154371019608:web:68718642a8f1a5f6560b2d',
    messagingSenderId: '154371019608',
    projectId: 'notepad-flutter-app',
    authDomain: 'notepad-flutter-app.firebaseapp.com',
    storageBucket: 'notepad-flutter-app.appspot.com',
    measurementId: 'G-RCPLVELS7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjB78Yayn9m4w_-8gq6cVNy21ozzYuX0',
    appId: '1:154371019608:android:2de8140170bc801c560b2d',
    messagingSenderId: '154371019608',
    projectId: 'notepad-flutter-app',
    storageBucket: 'notepad-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgqacQU65tFJlRaivTLrz-jdGIyjkLdM8',
    appId: '1:154371019608:ios:0f95ce85f3c3a984560b2d',
    messagingSenderId: '154371019608',
    projectId: 'notepad-flutter-app',
    storageBucket: 'notepad-flutter-app.appspot.com',
    iosClientId: '154371019608-bksgh9ocmn0chfc6l5qkplm4qkajq61p.apps.googleusercontent.com',
    iosBundleId: 'alsafi.harith.notepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgqacQU65tFJlRaivTLrz-jdGIyjkLdM8',
    appId: '1:154371019608:ios:0f95ce85f3c3a984560b2d',
    messagingSenderId: '154371019608',
    projectId: 'notepad-flutter-app',
    storageBucket: 'notepad-flutter-app.appspot.com',
    iosClientId: '154371019608-bksgh9ocmn0chfc6l5qkplm4qkajq61p.apps.googleusercontent.com',
    iosBundleId: 'alsafi.harith.notepad',
  );
}
